### ISSUE TITLE
Lack of community guidelines

### ISSUE THREAD

**Issue by lcw** [exanauts/ExaPF.jl#139]
When reviewing you JuliaCon submission, https://github.com/JuliaCon/proceedings-review/issues/72, I submitted a fix, https://github.com/exanauts/ExaPF.jl/pull/136, for an issue that was apparently already fixed on the [develop](https://github.com/exanauts/ExaPF.jl/tree/develop) branch.  It would be helpful if there were clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software, and 3) Seek support.

**Comment by frapac** [comment]
That's a very relevant remark, especially as our development workflow does not stick to Julia's standard (for instance, we are developing on `develop` instead of `master`). We should add at least a `CONTRIBUTING.md` document.
