### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by dmaldona** [exanauts/ExaPF.jl#20]
What do you guys think about documentation? Yes/No? If "Yes", any particular system that you prefer?

**Comment by frapac** [comment]
I think any documentation is good. But I would say this is not top priority at the moment, as we are still refactoring a lot the package. I would be in favor of putting more emphasis on docs if we start to have a stable API, or if we have new contributors to the package (e.g. interns). 
https://github.com/JuliaDocs/Documenter.jl is pretty good to generate documentation for Julia packages (readthedocs has fallen a bit out of favor in the Julia ecosystem).

**Comment by frapac** [comment]
PR #42 adds a first sketch for documentation, yet incomplete. 
It remains to write down: 
- [ ] A few paragraphs to explain the purpose and design of the package in `index.md`
- [ ] Add docstrings for `preconditioner.jl`
- [ ] Add docstrings for iterative solvers 
- [ ] Add a manual to explain the basic step to build up a problem from scratch when importing the data from matpower/PSSE

@dmaldona @michel2323

**Comment by dmaldona** [comment]
A new documentation system has been built.
