### ISSUE TITLE
Broken GPU example

### ISSUE THREAD

**Issue by cuihantao** [exanauts/ExaPF.jl#254]
Some API changes might have broken the Quick Start example for GPU at https://exanauts.github.io/ExaPF.jl/stable/quickstart/#How-to-deport-the-computation-on-the-GPU?

The file `examples/power_flow.jl` also fails at line 52. It looks like `ExaPF.jacobian_sparsity` is not a valid function. A function with a similar name is `_jacobian_sparsity` in `first_order.jl`. But as the name implies, it's supposed to be internal.

**Comment by frapac** [comment]
First, thanks for the constructive feedback. Indeed, you identified two issues with ExaPF: 
- the script `examples/power_flow.jl` is broken on master (addressed by #255 )
- the documentation is not built on the GPU, leading to confusion in the Quickstart section (with errors displayed in the output). @michel2323 how difficult it would be to build the doc on moonshot? The [following script](https://github.com/exanauts/ExaPF.jl/blob/master/test/quickstart.jl) should work, as a quick term solution. 


Long term, we should include more tutorials in the documentation to help new users getting a hand at ExaPF.

**Comment by cuihantao** [comment]
I'm about to make a PR to fix both issues. 

For the documentation, my fix is to change inside the GPU section 

```julia
polar_gpu = ExaPF.PolarForm(pf, CUDADevice())
```

to 

```julia
polar_gpu = ExaPF.PolarForm(polar, CUDADevice())

```

**Comment by frapac** [comment]
Any PR is welcomed on ExaPF. We appreciate your help.

**Comment by cuihantao** [comment]
Sure thing! On a side note, I tried to solve larger systems from MATPOWER but had little success. I tried to solve the `case_ACTIVSg10k.m`, `case_ACTIVSg25k.m`, etc. They either fail with overflow to `nan` or appear to be stuck in iterations. I also tried to tune the number of partitions, but that doesn't help.

Is this a known issue? I suspect it's the limitation of the iterative approach. I also tried the `ilu02` preconditioner on GPU outside ExaPF.jl but had no success.

**Comment by michel2323** [comment]
Fixed in https://github.com/exanauts/ExaPF.jl/pull/255. Thanks for reporting @cuihantao !

**Comment by michel2323** [comment]
@JuliaRegistrator register

**Comment by cuihantao** [comment]
@frapac Thank you very much for the suggestion! I will give cusolverRF a try.

**Comment by michel2323** [comment]
@cuihantao Just merged into master.
