### ISSUE TITLE
Iterative solvers are broken

### ISSUE THREAD

**Issue by frapac** [exanauts/ExaPF.jl#36]
It appears that changing the indexing of the Jacobian broke the iterative solvers.

**Comment by michel2323** [comment]
The Jacobian Jx was structurally symmetric (adjacency matrix is symmetric) before our reordering. By reordering the columns, the matrix is not symmetric anymore and the diagonal entries are 0. This worsens the Jacobi preconditioner which works best with a block diagonal structure (which is symmetric and matrix should be as diagonal dominant as possible).

I added some canonical tests and they seem to confirm that the preconditioner is implement correctly. The preconditioner also still works with the new ordering, however as the solution is worse, the Newton-Raphson is not able to converge with high enough accuracy.

Moreover, I think at some point we should look into an even better reordering and get a linear solver person involved.

I assign this to @dmaldona for now, as I think the solution for now is to switch back to the old ordering. I have a pushed the branch `dev/ordering`  , where you can switch between the old and new ordering by setting a global variable `debug` to `true` or `false`.

**Comment by frapac** [comment]
Fixed by #40
