### ISSUE TITLE
Preconditioner weights

### ISSUE THREAD

**Issue by michel2323** [exanauts/ExaPF.jl#81]
The preconditioner currently works without edge weights (all weights = 1). It would make sense to use the electrical distance as an edge weight. The Julia package [Metis.jl](https://github.com/JuliaSparse/Metis.jl) does only allow for vertex weights. The underlying Metis library supports edge weigths. A PR to Metis.jl would make sense.

**Comment by frapac** [comment]
Closing this issue as stalled.
